version: '3.9'
services:
  third-party:
    build: ./third-party
    environment:
      - min-delay-in-seconds=1
      - max-delay-in-seconds=3
#    ports:
#      - "8081:8080"
    networks:
      - internal_network

  sms:
    build: ./sms
    ports:
      - "8082:8080"
    networks:
      - internal_network

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=purchase-data
      - MYSQL_USER=purchase-data
      - MYSQL_PASSWORD=purchase-data-pass
    ports:
      - 3306:3306
    volumes:
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - internal_network

  redis:
    image: redis:6.0
#    ports:
#      - 6379:6379
    networks:
      - internal_network

  data-voucher:
    build: ./data-voucher
    ports:
      - "8083:8080"
    depends_on:
      - third-party
      - redis
    networks:
      - internal_network
      - external_network
    environment:
      - redis-host=redis
      - third-party-path=http://third-party:8080

networks:
  internal_network:
    internal: true
    driver: bridge
  external_network:
    driver: bridge
    internal: false


#  purchase-data:
#    image: myapp-image-name-that-appears-when-you-run-docker-images
#    restart: on-failure
#    depends_on:
#      - mysql
#    ports:
#      - 8080:8080
#    environment:
#      - DATABASE_HOST=myapp-mysql
#      - DATABASE_USER=myapp-user
#      - DATABASE_PASSWORD=password
#      - DATABASE_NAME=MyAppDb
#      - DATABASE_PORT=3306
